import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
export default function SettingsPage(props) {
    const { canControlSecurity, currentIpAddress, ipAccessRules, ipAccessLoading, ipAccessError, refreshIpAccessSettings, refreshSecurityControlState, settingsIpAddress, setSettingsIpAddress, settingsIpLabel, setSettingsIpLabel, settingsIpEnabled, setSettingsIpEnabled, onSaveIpAccessRule, isIpAccessSubmitting, ipRuleActionId, onToggleIpAccessRule, onDeleteIpAccessRule, securityLoading, isBusy, RefreshCwIcon, PhoneIcon, TrashIcon, isSecurityTokenValid, securityTokenRemainingSeconds, openSecurityStepUpModal, stepUpBusy, securityError, securityState, formatDate, securityReason, setSecurityReason, securityTargetUserId, setSecurityTargetUserId, users, session, onForceLogoutSelectedUser, onForceLogoutEveryone, onTapOff, onTapOn, showSecurityStepUpModal, setShowSecurityStepUpModal, stepUpPassword, setStepUpPassword, stepUpOtpRequested, onRequestSecurityStepUpOtp, stepUpOtp, setStepUpOtp, onVerifySecurityStepUpOtp, LockIcon } = props;
    if (!canControlSecurity) {
        return (_jsx("div", { className: "panel", style: { padding: 24 }, children: _jsx("div", { style: { color: "var(--ink-3)" }, children: "You do not have permission to use admin settings." }) }));
    }
    return (_jsxs(_Fragment, { children: [_jsxs("div", { style: { display: "grid", gap: 18 }, children: [_jsxs("div", { className: "panel", style: { padding: 20 }, children: [_jsxs("div", { style: { display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap", alignItems: "center", marginBottom: 16 }, children: [_jsxs("div", { children: [_jsx("h2", { style: { margin: 0, fontSize: 20, color: "var(--ink-1)" }, children: "Security access" }), _jsx("p", { style: { margin: "6px 0 0", color: "var(--ink-3)", fontSize: 14 }, children: "Verify your identity before changing access rules or running emergency controls." })] }), _jsx("button", { className: "btn btn-primary btn-sm", onClick: openSecurityStepUpModal, disabled: stepUpBusy, children: isSecurityTokenValid ? "Re-verify identity" : "Verify identity" })] }), _jsxs("div", { style: { display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }, children: [_jsx("span", { className: `badge ${isSecurityTokenValid ? "badge-active" : "badge-disabled"}`, children: isSecurityTokenValid ? "Privileged actions unlocked" : "Verification required" }), isSecurityTokenValid && (_jsxs("span", { style: { color: "var(--ink-4)", fontSize: 12 }, children: ["Token expires in ", securityTokenRemainingSeconds, "s"] }))] })] }), _jsxs("div", { className: "panel", style: { padding: 20 }, children: [_jsxs("div", { style: { display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap", alignItems: "center", marginBottom: 16 }, children: [_jsxs("div", { children: [_jsx("h2", { style: { margin: 0, fontSize: 20, color: "var(--ink-1)" }, children: "IP access control" }), _jsx("p", { style: { margin: "6px 0 0", color: "var(--ink-3)", fontSize: 14 }, children: "Disable a specific IP to block that network from using the app." })] }), _jsxs("button", { className: "btn btn-secondary btn-sm", onClick: () => void refreshIpAccessSettings(), disabled: ipAccessLoading || isIpAccessSubmitting || Boolean(ipRuleActionId), children: [_jsx(RefreshCwIcon, { size: 14, style: { marginRight: 4 } }), ipAccessLoading ? "Refreshing..." : "Refresh rules"] })] }), _jsxs("div", { style: { display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap", marginBottom: 14 }, children: [_jsx("span", { className: "badge badge-active", children: "Current IP" }), _jsx("span", { style: { fontSize: 13, color: "var(--ink-2)", fontWeight: 600 }, children: currentIpAddress ?? "Unavailable" })] }), ipAccessError && (_jsx("div", { style: { marginBottom: 14, color: "var(--red)", fontSize: 13 }, children: ipAccessError })), _jsxs("div", { style: {
                                    display: "grid",
                                    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
                                    gap: 12,
                                    alignItems: "end",
                                    marginBottom: 18
                                }, children: [_jsxs("div", { children: [_jsx("label", { style: { display: "block", fontSize: 12, color: "var(--ink-4)", fontWeight: 600, marginBottom: 6 }, children: "IP address" }), _jsx("input", { className: "modal-input", type: "text", value: settingsIpAddress, onChange: (event) => setSettingsIpAddress(event.target.value), placeholder: "203.110.90.15", style: { margin: 0 } })] }), _jsxs("div", { children: [_jsx("label", { style: { display: "block", fontSize: 12, color: "var(--ink-4)", fontWeight: 600, marginBottom: 6 }, children: "Label" }), _jsx("input", { className: "modal-input", type: "text", value: settingsIpLabel, onChange: (event) => setSettingsIpLabel(event.target.value), placeholder: "Office broadband", style: { margin: 0 } })] }), _jsxs("div", { children: [_jsx("label", { style: { display: "block", fontSize: 12, color: "var(--ink-4)", fontWeight: 600, marginBottom: 6 }, children: "Access" }), _jsxs("select", { value: settingsIpEnabled ? "enabled" : "disabled", onChange: (event) => setSettingsIpEnabled(event.target.value === "enabled"), style: {
                                                    width: "100%",
                                                    borderRadius: 10,
                                                    border: "1px solid var(--border)",
                                                    background: "var(--surface)",
                                                    color: "var(--ink-1)",
                                                    padding: "12px 14px",
                                                    minHeight: 46
                                                }, children: [_jsx("option", { value: "disabled", children: "Disabled (block)" }), _jsx("option", { value: "enabled", children: "Enabled (allow)" })] })] }), _jsx("button", { className: "btn btn-primary", onClick: () => void onSaveIpAccessRule(), disabled: isIpAccessSubmitting || Boolean(ipRuleActionId), style: { minHeight: 46 }, children: isIpAccessSubmitting ? "Saving..." : "Save rule" })] }), ipAccessRules.length === 0 ? (_jsx("div", { style: {
                                    border: "1px dashed var(--border)",
                                    borderRadius: 12,
                                    padding: 18,
                                    color: "var(--ink-4)",
                                    fontSize: 13
                                }, children: "No IP rules yet. Add one above to start blocking or re-enabling a network." })) : (_jsx("div", { style: { display: "grid", gap: 12 }, children: ipAccessRules.map((rule) => {
                                    const isCurrentIp = Boolean(currentIpAddress && currentIpAddress === rule.ipAddress);
                                    const rowBusy = ipRuleActionId === rule.id;
                                    return (_jsx("div", { style: {
                                            border: "1px solid var(--border)",
                                            borderRadius: 14,
                                            padding: 16,
                                            background: rule.enabled
                                                ? "color-mix(in srgb, var(--green) 7%, var(--surface))"
                                                : "color-mix(in srgb, var(--red) 8%, var(--surface))"
                                        }, children: _jsxs("div", { style: { display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap", alignItems: "flex-start" }, children: [_jsxs("div", { style: { display: "grid", gap: 8 }, children: [_jsxs("div", { style: { display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center" }, children: [_jsx("span", { style: { fontSize: 16, fontWeight: 700, color: "var(--ink-1)" }, children: rule.ipAddress }), _jsx("span", { className: `badge ${rule.enabled ? "badge-active" : "badge-disabled"}`, children: rule.enabled ? "Enabled" : "Disabled" }), isCurrentIp && (_jsx("span", { className: "badge", style: { background: "var(--accent-soft)", color: "var(--accent)" }, children: "Current network" }))] }), _jsx("div", { style: { fontSize: 13, color: "var(--ink-3)" }, children: rule.label || "No label provided" }), _jsxs("div", { style: { fontSize: 12, color: "var(--ink-4)" }, children: ["Updated ", formatDate(rule.updatedAt), rule.updatedByEmail ? ` by ${rule.updatedByEmail}` : ""] })] }), _jsxs("div", { style: { display: "flex", gap: 8, flexWrap: "wrap" }, children: [_jsx("button", { className: `btn ${rule.enabled ? "btn-danger" : "btn-primary"} btn-sm`, onClick: () => void onToggleIpAccessRule(rule), disabled: rowBusy || isIpAccessSubmitting, children: rowBusy ? "Saving..." : rule.enabled ? "Disable access" : "Enable access" }), _jsxs("button", { className: "btn btn-secondary btn-sm", onClick: () => void onDeleteIpAccessRule(rule), disabled: rowBusy || isIpAccessSubmitting, children: [_jsx(TrashIcon, { size: 14, style: { marginRight: 4 } }), "Delete"] })] })] }) }, rule.id));
                                }) }))] }), _jsxs("div", { className: "panel", style: { padding: 20 }, children: [_jsxs("div", { style: { display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap", alignItems: "center", marginBottom: 18 }, children: [_jsxs("div", { children: [_jsx("h2", { style: { margin: 0, fontSize: 20, color: "var(--ink-1)" }, children: "Emergency controls" }), _jsx("p", { style: { margin: "6px 0 0", color: "var(--ink-3)", fontSize: 14 }, children: "Targeted logout, global logout, and tap-off controls for high-risk events." })] }), _jsxs("button", { className: "btn btn-secondary btn-sm", onClick: () => void refreshSecurityControlState(), disabled: securityLoading || isBusy, children: [_jsx(RefreshCwIcon, { size: 14, style: { marginRight: 4 } }), securityLoading ? "Refreshing..." : "Refresh state"] })] }), securityError && (_jsx("div", { style: { marginBottom: 12, color: "var(--red)", fontSize: 13 }, children: securityError })), _jsxs("div", { style: { display: "grid", gap: 14, gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", marginBottom: 18 }, children: [_jsxs("div", { className: "panel", style: { margin: 0 }, children: [_jsx("div", { style: { fontSize: 12, color: "var(--ink-4)", marginBottom: 6 }, children: "Tap-off status" }), _jsx("div", { style: { fontSize: 18, fontWeight: 700, color: securityState?.tapOffActive ? "var(--red)" : "var(--green)" }, children: securityState?.tapOffActive ? "ACTIVE" : "INACTIVE" }), _jsxs("div", { style: { marginTop: 6, fontSize: 12, color: "var(--ink-4)" }, children: ["Started: ", securityState?.tapOffStartedAt ? formatDate(securityState.tapOffStartedAt) : "Verify to load"] })] }), _jsxs("div", { className: "panel", style: { margin: 0 }, children: [_jsx("div", { style: { fontSize: 12, color: "var(--ink-4)", marginBottom: 6 }, children: "Global logout cutoff" }), _jsx("div", { style: { fontSize: 13, fontWeight: 600, color: "var(--ink-2)" }, children: securityState?.globalLogoutAfter ? formatDate(securityState.globalLogoutAfter) : "Verify to load" }), _jsxs("div", { style: { marginTop: 6, fontSize: 12, color: "var(--ink-4)" }, children: ["Last tap-off by: ", securityState?.tapOffBy ?? "-"] })] })] }), _jsxs("div", { style: { display: "grid", gap: 12, marginBottom: 16 }, children: [_jsx("label", { style: { fontSize: 12, color: "var(--ink-4)", fontWeight: 600 }, children: "Reason for security action" }), _jsx("textarea", { value: securityReason, onChange: (event) => setSecurityReason(event.target.value), placeholder: "Reason for audit trail...", style: {
                                            minHeight: 80,
                                            resize: "vertical",
                                            borderRadius: 10,
                                            border: "1px solid var(--border)",
                                            background: "var(--surface)",
                                            color: "var(--ink-1)",
                                            padding: "10px 12px"
                                        } })] }), _jsxs("div", { style: { display: "grid", gap: 12, marginBottom: 16 }, children: [_jsx("label", { style: { fontSize: 12, color: "var(--ink-4)", fontWeight: 600 }, children: "Target user for single-account logout" }), _jsxs("div", { style: { display: "flex", gap: 10, flexWrap: "wrap" }, children: [_jsxs("select", { value: securityTargetUserId, onChange: (event) => setSecurityTargetUserId(event.target.value), style: {
                                                    minWidth: 260,
                                                    borderRadius: 10,
                                                    border: "1px solid var(--border)",
                                                    background: "var(--surface)",
                                                    color: "var(--ink-1)",
                                                    padding: "10px 12px"
                                                }, children: [_jsx("option", { value: "", children: "Select a user..." }), users
                                                        .filter((user) => user.id !== session?.user?.id)
                                                        .map((user) => (_jsx("option", { value: user.id, children: user.email }, user.id)))] }), _jsx("button", { className: "btn btn-secondary btn-sm", onClick: () => void onForceLogoutSelectedUser(), disabled: isBusy || !securityTargetUserId, children: "Logout selected user" })] })] }), _jsxs("div", { style: { display: "flex", gap: 10, flexWrap: "wrap" }, children: [_jsx("button", { className: "btn btn-secondary btn-sm", onClick: () => void onForceLogoutEveryone(), disabled: isBusy, children: "Logout everyone" }), _jsx("button", { className: "btn btn-danger btn-sm", onClick: () => void onTapOff(), disabled: isBusy || Boolean(securityState?.tapOffActive), children: "Activate tap-off" }), _jsx("button", { className: "btn btn-primary btn-sm", onClick: () => void onTapOn(), disabled: isBusy || !securityState?.tapOffActive, children: "Restore service" })] })] })] }), showSecurityStepUpModal && (_jsx("div", { className: "modal-overlay", onClick: () => (!stepUpBusy ? setShowSecurityStepUpModal(false) : undefined), children: _jsxs("div", { className: "modal", onClick: (event) => event.stopPropagation(), style: { maxWidth: 420 }, children: [_jsx("div", { className: "modal-title", children: "Verify identity" }), _jsx("div", { className: "modal-desc", children: "Confirm your password and SMS OTP to unlock privileged actions." }), _jsxs("div", { className: "input-group", style: { marginBottom: 12 }, children: [_jsx("span", { className: "input-icon", children: _jsx(LockIcon, {}) }), _jsx("input", { type: "password", placeholder: "Current password", value: stepUpPassword, onChange: (event) => setStepUpPassword(event.target.value), disabled: stepUpBusy })] }), !stepUpOtpRequested ? (_jsx("button", { className: "btn btn-primary", onClick: () => void onRequestSecurityStepUpOtp(), disabled: stepUpBusy || !stepUpPassword, style: { width: "100%", marginBottom: 12 }, children: stepUpBusy ? "Requesting..." : "Send OTP" })) : (_jsxs(_Fragment, { children: [_jsxs("div", { className: "input-group", style: { marginBottom: 12 }, children: [_jsx("span", { className: "input-icon", children: _jsx(PhoneIcon, {}) }), _jsx("input", { type: "text", placeholder: "Enter 6-digit OTP", value: stepUpOtp, onChange: (event) => setStepUpOtp(event.target.value), disabled: stepUpBusy, maxLength: 6 })] }), _jsx("button", { className: "btn btn-primary", onClick: () => void onVerifySecurityStepUpOtp(), disabled: stepUpBusy || !stepUpOtp, style: { width: "100%", marginBottom: 10 }, children: stepUpBusy ? "Verifying..." : "Verify & unlock" }), _jsx("button", { className: "btn btn-secondary btn-sm", onClick: () => void onRequestSecurityStepUpOtp(), disabled: stepUpBusy, style: { width: "100%" }, children: "Resend OTP" })] }))] }) }))] }));
}
